#!/usr/bin/env bash
# =============================================================================
# GPU Auto-Detection & Docker Compose Override Generator
#
# Detects the host GPU vendor (NVIDIA / AMD / none) and generates
# docker/docker-compose.gpu.yml with the correct PyTorch wheel index
# and device passthrough configuration.
#
# Usage:  bash docker/setup-gpu.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GPU_COMPOSE="$SCRIPT_DIR/docker-compose.gpu.yml"

# -----------------------------------------------------------------------------
# Detection
# -----------------------------------------------------------------------------
detect_gpu() {
    # 1. NVIDIA — nvidia-smi is the most reliable indicator
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
        echo "nvidia"
        return
    fi

    # 2. AMD ROCm — /dev/kfd means the amdgpu kernel driver is loaded
    if [ -e /dev/kfd ]; then
        echo "amd"
        return
    fi

    # 3. Fallback — check lspci for GPU hardware (driver may not be ready)
    if command -v lspci &>/dev/null; then
        if lspci | grep -qi 'nvidia'; then
            echo "nvidia-no-driver"
            return
        elif lspci | grep -qi 'amd.*radeon\|amd.*navi\|advanced micro.*display\|advanced micro.*vga'; then
            echo "amd-no-driver"
            return
        fi
    fi

    echo "cpu"
}

# -----------------------------------------------------------------------------
# Generate compose override
# -----------------------------------------------------------------------------
GPU_VENDOR=$(detect_gpu)

case "$GPU_VENDOR" in
    nvidia)
        cat > "$GPU_COMPOSE" << 'EOF'
# Auto-generated by setup-gpu.sh — do not commit
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      args:
        PYTORCH_INDEX_URL: https://download.pytorch.org/whl/cu124
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
EOF
        echo "[GPU] NVIDIA GPU detected."
        echo "[GPU] PyTorch will be built with CUDA 12.4 support."
        echo ""
        echo "Build and run with:"
        echo "  cd docker && docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d --build api"
        ;;

    nvidia-no-driver)
        echo "[GPU] NVIDIA GPU detected but nvidia-smi is not available."
        echo "[GPU] Install the NVIDIA Container Toolkit first:"
        echo "  https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
        echo ""
        echo "Then re-run:  bash docker/setup-gpu.sh"
        exit 1
        ;;

    amd)
        # Resolve numeric GIDs — group names may not exist inside the container
        VIDEO_GID=$(getent group video 2>/dev/null | cut -d: -f3 || echo "44")
        RENDER_GID=$(getent group render 2>/dev/null | cut -d: -f3 || echo "")

        GROUP_ADD="      - \"${VIDEO_GID}\""
        if [ -n "$RENDER_GID" ]; then
            GROUP_ADD="${GROUP_ADD}
      - \"${RENDER_GID}\""
        fi

        cat > "$GPU_COMPOSE" << EOF
# Auto-generated by setup-gpu.sh — do not commit
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      args:
        PYTORCH_INDEX_URL: https://download.pytorch.org/whl/rocm6.2
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
${GROUP_ADD}
EOF
        echo "[GPU] AMD GPU detected (ROCm)."
        echo "[GPU] PyTorch will be built with ROCm 6.2 support."
        echo ""
        echo "Build and run with:"
        echo "  cd docker && docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d --build api"
        ;;

    amd-no-driver)
        echo "[GPU] AMD GPU detected but /dev/kfd is not available."
        echo "[GPU] Install the amdgpu driver and ROCm stack first:"
        echo "  https://rocm.docs.amd.com/projects/install-on-linux/en/latest/"
        echo ""
        echo "Then re-run:  bash docker/setup-gpu.sh"
        exit 1
        ;;

    cpu)
        rm -f "$GPU_COMPOSE"
        echo "[GPU] No supported GPU detected. Using CPU-only mode."
        echo ""
        echo "Run with:"
        echo "  cd docker && docker compose up -d"
        ;;
esac
